variables:

  threads:
    # If no default value is specified,
    # if your "cluster name" is not 'mypc1' or 'mypc2',
    # the `configure` command will fail
    default: [1]
    per_cluster:
      mypc1: [2]
      mypc2: [4, 6]

  variant:
    default: ['defaultVariant'] 
    map:
      4: ['4threads_variant_1', '4threads_variant_2']
      6: ['6threads_only_variant']

mypc1:
  scheduler: local
  configs:
    - name: "{threads}_threads"
      env:
        - "OMP_NUM_THREADS={threads}"


mypc2:
  scheduler: local
  configs:
    - name: "{threads}_threads"
      env:
        - "OMP_NUM_THREADS={threads}"
    

    - name: "{threads}_threads_{variant[threads]}"
      env:
        - "OMP_NUM_THREADS={threads}"
        - 'VARIANT_NAME="{variant[threads]}"'


mypcDefaultArgs:
  scheduler: local
  configs:
    - name: "1_threads"
      env:
        - "OMP_NUM_THREADS=1"
