variables:
  threads: [1, 2, 4, 8, 16]

local:
  scheduler: local

  configs:
    # The {threads} symbol is a wildcard that will be substituted
    - name: "{threads}_threads"
      env:
        - "OMP_NUM_THREADS={threads}"
